In [3]:
# load and show an image with Pillow
from PIL import Image

# Open the image from working directory
image = Image.open("tiger.png")
# summarize some details about the image
print(image.format)
print(image.size)
print(image.mode)
# show the image
image.show()

PNG
(1280, 720)
RGB


In [6]:
from numpy import asarray

# Convert image to numpy  array
data = asarray(image)
print(type(data))
print(data.shape)

<class 'numpy.ndarray'>
(720, 1280, 3)


In [9]:
# create Pillow image
img = Image.fromarray(data)
print(type(img))
img.show()

<class 'PIL.Image.Image'>


In [11]:
print(img.mode)
print(img.size)

RGB
(1280, 720)


In [12]:
print(data)

[[[164 160 159]
  [165 161 160]
  [164 163 161]
  ...
  [160 128  90]
  [158 125  90]
  [161 128  93]]

 [[164 160 159]
  [164 160 159]
  [163 162 160]
  ...
  [164 132  94]
  [162 129  94]
  [157 124  89]]

 [[163 159 156]
  [164 160 157]
  [163 162 160]
  ...
  [164 132  94]
  [162 129  94]
  [157 124  89]]

 ...

 [[ 93  94  96]
  [ 93  94  96]
  [ 92  93  95]
  ...
  [120 116 107]
  [121 117 108]
  [122 118 109]]

 [[ 93  94  96]
  [ 93  94  96]
  [ 92  93  95]
  ...
  [120 116 107]
  [121 117 108]
  [122 118 109]]

 [[ 93  94  96]
  [ 93  94  96]
  [ 92  93  95]
  ...
  [119 115 106]
  [121 117 108]
  [122 118 109]]]
